NSCC-ITC-Winter2025-WEBD3031-700-MCa/webd3031-project-culturalcompass

src/components/Layout/Header/index.tsx
fix(route.js): fix media signin signout. fixed #37
=> fix(route.js): fix media signin signout

prisma/migrations/20250317191014_init/migration.sql, prisma/schema.prisma, src/app/api/auth/[...nextauth]/route.js, src/app/api/auth/register.js
fix(route.js): implement SignIn SignOut function. Fixed #45
=> fix(route.js): implement SignIn SignOut function

package-lock.json, package.json, src/app/api/checkout-session/route.js, src/app/cancel/page.js, src/app/success/page.js, src/components/Home/Features/index.tsx, tsconfig.json
=> feat(payment): implement payment processing functionality

src/app/api/auth/[...nextauth]/route.js
=> fix(route.js): validation for signin/signout

src/app/api/webhook/route.js
=> feat: integrate Stripe webhook to upgrade users to premium after payment

next-auth.d.ts, src/app/dashboard/Dashboard.js, src/app/dashboard/UserGrowthChart.js, src/app/dashboard/page.js, src/components/Layout/Header/index.tsx
=> fix: Fixed dashboard CSS and navbar routes

src/app/api/auth/[...nextauth]/route.js, src/app/api/webhook/route.js, src/types/next-auth.d.ts
=> feat: integrate Stripe webhook test

next-auth.d.ts, src/app/(site)/showCountries/page.tsx, src/app/api/auth/[...nextauth]/route.js, src/components/Layout/Header/index.tsx
After payment the user has been paid can access all the contents. fixed #27
=> fix: show the content if is_premium = true

src/app/api/webhook/route.js
=> feat: Implement Stripe checkout session and webhook

src/app/api/webhook/route.js
=> fix: trying to make the webhook work n

src/app/api/auth/[...nextauth]/route.js, src/app/success/page.js
=> fix: session for premium updated

src/app/api/auth/[...nextauth]/route.js
=> Sessionreset

.github/workflows/accessibility-check.yml
=> feat: create accessibility-check.yml

src/app/api/webhook/route.js
=> fix: trying to reset session after payment

src/app/api/webhook/route.js
=> fix: update code to reset session after payment

src/app/api/webhook/route.js
=> fix: update code to reset session after payment3

src/app/api/webhook/route.js
=> fix: refreshing the session after payment

src/app/api/webhook/route.js, src/app/success/page.js
=> fix: refreshing the session after payment2

src/app/api/auth/[...nextauth]/route.js, src/app/api/refresh-session/route.js, src/app/success/page.js
=> fix(auth): ensure session reflects latest is_premium status from DB

src/app/dashboard/UserGrowthChart.js
=> fix:Dashboardchartagain
